### ISSUE TITLE
No such file or directory when running setup_linuxmod.sh

### ISSUE THREAD

**Issue by connortaumoepeau** [505e06b2/FrostyToolsuite-Linux#1]
Hey thanks for writing up this guide. I'm currently trying to follow this on my steam deck. I get the following errors when running setup_linuxmod.sh

ln: failed to create symbolic link 'LinuxMod/patch/win32/configurations/superbundleinstallpackage/': No such file or directory
ln: failed to create symbolic link 'LinuxMod/patch/win32/configurations/superbundleinstallpackage2/': No such file or directory
ln: failed to create symbolic link 'LinuxMod/patch/win32/levels/frontend/': No such file or directory
ln: failed to create symbolic link 'LinuxMod/patch/win32/levels/mainlevel/': No such file or directory
ln: failed to create symbolic link 'LinuxMod/patch/win32/loc/': No such file or directory
ln: failed to create symbolic link 'LinuxMod/patch/win32/': No such file or directory

**Comment by 505e06b2** [comment]
I'm able to replicate this if I change Line 3 of the setup_linuxmod script to an incorrect value - try setting this to your Frosty profile relative path?

If you're using the Mod Manager, this will likely be `ModData/Default`, but it will depend on the profile

**Comment by 505e06b2** [comment]
I have now altered the script to display more useful information, instead of spamming the terminal - feel free to [test it out](https://github.com/505e06b2/FrostyToolsuite-Linux/blob/38aa379e6051bebf6a53b61addc313618a259870/setup_linuxmod_nfs-heat.sh) if you're still having trouble

**Comment by 505e06b2** [comment]
Closing as no further communication in about 2 weeks

**Comment by Hollyrious** [comment]
Also getting this.
